### ISSUE TITLE
Suggestion for minor corrections

### ISSUE THREAD

**Issue by melpetera** [workflow4metabolomics/tools-metabolomics#111]
Hi @lecorguille !
Very nice work for this XCMS3 Galaxy version :)
Please find here some minor corrections I suggest to complete this all-brand-new XCMS workflow

- [ ] 1) Concerning the NA to 0 new option, the option works well! I would just suggest minor text modification for name and mini-help, for it not to be equivocal. I suggest "If NA values still remain, replace them by 0 in the dataMatrix" and "Some downstream tools (data processing, statistics) may not accept NA values". What do you think about it?

- [ ] 2) Concerning findChromPeaks, since now it is more than ever recommanded to use individual files to process data, I would recommand to add as an output a tabular file with the extracted info for the concerned extracted sample. Beware: this is only compatible when using individual files (for zip it would be strange to do so). Here the command line to extract this information: `write.table(chromPeaks(xdata), file="EchX_extracted.or.whatever.txt", quote=FALSE, row.names=FALSE, sep="\t")`

- [ ] 3) I noticed that in the groupChromPeak pdf output, sample groups were not taken into account (see picture below). You can see that the legend is right, but there is only one colour for points although it was suppose to have two. 

![pb_couleur_plot_group](https://user-images.githubusercontent.com/20553061/46483007-fd477100-c7f6-11e8-8e3e-6ad822baccc1.png)

- [ ] 4) I noticed that in the plot chromatogram module, only 3 colours are available: if you have 4 groups, one will be in an invisible colour. 

That's all. Any comment is welcome. @yguitton and @jfrancoismartin do not hesitate to give your opinion.

Bonus: there is a "i" missing in Centwave's mzCenterFun parameter at the begining of the fourth choice.

**Comment by SylvainChereau** [comment]
I faced the exact  same issue (only red dots) and yes above 3 diffrents groups ==> no color assigned
![image](https://user-images.githubusercontent.com/29650570/46485832-c3796900-c7fc-11e8-97cd-4fe039b5b906.png)

**Comment by melpetera** [comment]
PR 181 addresses points 1 to 3.

Point 4 is already handled by last prod version: I checked with 4 classes and it worked. 

Once PR is accepted and new version is on prod instance, some quick tests using Galaxy should be enough to close this issue.

**Comment by lecorguille** [comment]
xref: https://github.com/workflow4metabolomics/tools-metabolomics/pull/181

**Comment by lecorguille** [comment]
The tools have been updated on workflow4metabolomics.usegalaxy.fr, can you check them @melpetera before updating them on the "current" instance ?

**Comment by melpetera** [comment]
Tested and approuved 👍 

Here we go, thanks @lecorguille 😃

**Comment by lecorguille** [comment]
Cool
