### ISSUE TITLE
Tag disappearance

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/tools-metabolomics#162]
The tag `v3.4.4` has disappeared from this repository. It is required by `w4m-vm` to build the production version of the VM. Why has it been deleted? Was there any trouble with this tag?
Also the branch `dev` has disappeared and it was used to build the development version of the VM.
Should `master` be used for the development version?
I don't think it possible to restore the tag. What should I use for the production version? A fixed version (tag) is required for it.

CC: @fgiacomoni

**Comment by lecorguille** [comment]
Yes, you won't like that but there aren't any dev branch anymore.
Just some features branches to submit PR and the master.

We were agree that the Galaxy wrappers themselves don't need to have complicate mechanisms.
If we really need some alpha/beta/release states, it will be around proper R scripts and packages.
Our plan is indeed to extract as many codes from this repository and just keep the Galaxy xml wrappers and some light R wrappers to deal with the arguments.

**Comment by pkrog** [comment]
I don't mind the deletion of the `dev` branch, it's your repos.
It's just that w4m-vm used the tag, and now it's broken. I don't know what to do.
Is `master` to be considered the dev branch?
How do you track which commit was used to publish to the toolshed? It's this commit I need to know for the production branch.

**Comment by bgruening** [comment]
I can share our experience from the IUC and tools-galaxyp world. We do not have any dev branch in any of those multi-tool repositories. Everything that hits master gets deployed to test- and main toolshed. Direct commits to master are forbidden, everything needs to go over PRs and those gets linted and tested via planemo. So everything that passes the testing is good to be deployed.
Then we have tools.yml files, simple lists of tools that we use to build VMs and Containers. 

If you need a snapshot of the master branch at a given commit you can always reference the commit directly, e.g. https://github.com/workflow4metabolomics/tools-metabolomics/archive/d73f3664336def878419e019920d209f3bfb4fa9.tar.gz

Our experience is that this workflow is way more efficient that going with a dev branch.

**Comment by pkrog** [comment]
Hi Björn, the point of my issue was about a tag that was removed, and that should never have happened. Anyway I will try to switch to installing tools from the main tool shed, for the production version, using Ansible, so that should avoid that issue in the future.
About the dev branch, the idea is to be able to build a VM with tools not on the tool shed, so you can test your tool inside a VM for development purposes before publishing to the test tool shed. Any branch can be used, master, dev or another one.

**Comment by bgruening** [comment]
Yes the tag is unfortunately, I tried to answer the dev/master branch questions and tried to be constructive and just share my experience.

If you have a local checkout ... you probably have the tag still right? Next to the tag is a hashsum associated, this you can use to point your VM to I think.

**Comment by lecorguille** [comment]
@pkrog Sorry for that.
Since I renamed the xcms repo in tools-metabolomics, it was strange to keep the tags.
I can duplicate this repo and restore (and archive) the xcms one as it was before the renaming and restore the tags (if we can spot the good commit tags)?

**Comment by pkrog** [comment]
Yes @bgruening , I understandm thanks for sharing your experience which I totally agree with.
Do not mind anymore @lecorguille , I've used the master branch to build a production instance of the VM for @fgiacomoni and @cduperier . As I said, I will try to use toolshed versions for the production instance in the future (near future I hope), so I should not use tags anymore. I close this issue, since it is solved for me. Thanks to all.
