### ISSUE TITLE
xcms_chrom_plot missing color in group plot

### ISSUE THREAD

**Issue by CedricDelporte** [workflow4metabolomics/tools-metabolomics#171]
Hello,

We put four group in our second column in the sampleMetadata file (class) and so there are 4 groups.
The fourth group does not appear in the group chromatogram (or is in white).
[téléchargement.pdf](https://github.com/workflow4metabolomics/tools-metabolomics/files/4153966/telechargement.pdf)

**Comment by lecorguille** [comment]
Can you share your history with me?

**Comment by lecorguille** [comment]
Me bad: https://github.com/workflow4metabolomics/tools-metabolomics/pull/155/commits/098f413b1373dd9fd3671c5f3659f8abca2b0195
Should be fixed.
Thanks @CedricDelporte for the report
