### ISSUE TITLE
Please wrap the XCMS refineChromPeaks tool

### ISSUE THREAD

**Issue by eschen42** [workflow4metabolomics/tools-metabolomics#193]
The XCMS `refineChromPeaks-merge` tool ([https://rdrr.io/bioc/xcms/man/refineChromPeaks-merge.html](https://rdrr.io/bioc/xcms/man/refineChromPeaks-merge.html)) was added to the XCMS suite to help with irregularly shaped peaks such as are encountered in HILIC data.  I would l like to use this tool in Galaxy workflows.  I see nothing in the toolshed or in this repository; hence this request.

**Comment by eschen42** [comment]
@lecorguille I can imagine at least two ways to approach this:

- Add code to `xcms_xcmsSet.r` along with options in the wrapper to set the parameters
- Create a separate tool

I can start working on the first and give you a pull request.  You can let me know whether you would prefer to pursue another option or would like to delegate this to someone else.

**Comment by eschen42** [comment]
@lecorguille I have been reading the [XCMS reference manual](https://bioconductor.org/packages/release/bioc/manuals/xcms/man/xcms.pdf) and have learned that refineChromPeaks can be used for three things:

- Remove chromatographic peaks with too large rt width
- Remove chromatographic peaks based on intensity
- Merge neighboring and overlapping chromatographic peaks 

This seriously calls into question my suggestion of integrating it into xcmsSet, so now I am under the impression that creating a separate tool is the better approach.

What do you think?

**Comment by lecorguille** [comment]
Hi Art,

It's indeed a balance between modularity and complexity.
Is this tool between, findChromPeaks and groupChromPeaks?

Ping @workflow4metabolomics/ms , do you have an idea?

**Comment by eschen42** [comment]
@lecorguille Yes, the tool is between findChromPeaks and groupChromPeaks

I have gotten this to work in my fork of `tools-metabolomics`, wrapped as a separate tool `xcms_refine` at

https://github.com/eschen42/tools-metabolomics/commit/2f3f29dbaaa8568b40818d3476159c384f1a21d6

It passes `planemo test .` and runs correctly in `planemo serve .`; I still need to stress test it a bit more before sending a pull request to solicit feedback formally.  But, hey, it's working!  The drawbacks are:

- It is dependent on `bioconductor-xcms 3.12.0` because `refineChromPeaks` is not found in `3.6.1`
- It generates warnings because R 4.0.2 runs but `bioconductor-xcms 3.12.0`  was built with R 4.0.3

So, we will need to figure out how to negotiate around this obstacle.  It strongly argues against integrating with (and de-stabilizing) the `findChromPeaks` wrapper.

Thank you for any guidance or suggestions that you can provide.

**Comment by yguitton** [comment]
Hi

Never tried that function, but would be nice to add some of the new xcms
functions in the pipeline.

Thanks Art for your work.

Best
Yann

**Comment by melpetera** [comment]
Hi @eschen42 

Thank you for the detailed feedback!
I have not tested this function yet, but based on your detailed description, I agree with your suggestion to consider it as a dedicated tool. May I have understood correctly, the function can take as input an object generated by a first findChromPeaks run, and "refine" it to obtain as output a similar object, "filtered" according to the parameters passed to the refineChromPeaks-merge function. Right?

Mélanie

**Comment by eschen42** [comment]
@melpetera You have exactly understood.  For further info, please see the three functionalities of refineChromPeaks documented in the "manual" (the first is the one that I need at the moment, but it seemed sensible to wrap all three):

- https://rdrr.io/bioc/xcms/man/refineChromPeaks-merge.html
- https://rdrr.io/bioc/xcms/man/refineChromPeaks-clean.html
- https://rdrr.io/bioc/xcms/man/refineChromPeaks-filter-intensity.html

**Comment by eschen42** [comment]
@lecorguille @melpetera 
I found a bit of a "showstopper": because `refineChromPeaks` was not available in XCMS 3.6.1, I wrapped the (proposed) `xcms_refine` tool with a dependency on XCMS 3.12.0.  Unfortunately, the `.RData` file that this produces has an incompatibility with XCMS 3.6.1, so that `xcms_merge` threw an error when trying to consume the `.RData` file.

So, it seems that this is blocked until other tools in the suite run under XCMS 3.12.0

**Comment by lecorguille** [comment]
Sure, we have to bump the xcms version for all the wrappers.
Can you submit a PR ?

And indeed, unfortunately, we will have to update the different test_data RData :/

**Comment by eschen42** [comment]
@lecorguille Okay, if I understand you, I can submit a PR for this tool.

Here is the question that I have is what to do about the dependency on XCMS 3.12.0, since ordinarily this is handled through the macros.  Should I hard code it into the PR and then you fix it during the merge after the switch to XCMS 3.12.0 ?

Fortunately, it accepts the 3.6.1 test data as input because Johannes Reiner made `refineChromPeaks` backward compatible.

**Comment by eschen42** [comment]
@lecorguille @melpetera I am awaiting clarification on the content for a PR. Thank you.

> @lecorguille Okay, if I understand you, I can submit a PR for this tool.
> 
> Here is the question that I have is what to do about the dependency on XCMS 3.12.0, since ordinarily this is handled through the macros. Should I hard code it into the PR and then you fix it during the merge after the switch to XCMS 3.12.0 ?
> To put it another way, are we tracking the needed work and our dialog in a PR ?
> 
> Fortunately, it accepts the 3.6.1 test data as input because Johannes Reiner made `refineChromPeaks` backward compatible.

**Comment by lecorguille** [comment]
Sorry, I though that I had already answer. It seems that I never press the green button.

Yes, we should just starting by bumping the xcms version in the macro.
My guess that the new CI workflow will raise a LOT of R linting errors :( 
But after that, we will be able to have an idea about the planemo test themself.

**Comment by lecorguille** [comment]
Let see what will happen here: https://github.com/workflow4metabolomics/tools-metabolomics/pull/194

**Comment by eschen42** [comment]
@lecorguille Good news! Thank you very much! I will try to keep an eye on when #194 gets closed.
