### ISSUE TITLE
Error when linking Isocor and Isoplot in a workflow

### ISSUE THREAD

**Issue by llegregam** [workflow4metabolomics/tools-metabolomics#203]
I just finished getting the tool Isoplot online, and I tried linking it with Isocor in a workflow. The Isocor output file format is .tsv (tabular), but it seems that even though Isoplot accepts tabular and csv inputs, Galaxy will not let me link them together. Is this normal behaviour?

**Comment by llegregam** [comment]
Yes of course! The output of isocor that needs to be linked to isoplot can be found here: 
https://toolshed.g2.bx.psu.edu/repos/gmat/isocor/file/fa183805db31/isocor.xml
And here is a snapshot of it:
![image](https://user-images.githubusercontent.com/75795040/133217162-9add8d62-ef05-4175-b35a-31ad66252d83.png)
The output is line 54 (output1, tabular format). 

It is supposed to be linked to isoplot's data input (line 20):
![Capture](https://user-images.githubusercontent.com/75795040/133216993-23d63e6f-8a3b-479f-ac98-6cf358a54765.JPG)

Thanks!

**Comment by llegregam** [comment]
Hello! Just wondering if there is any new info on the bug

**Comment by lecorguille** [comment]
Strange!
Can you share an history on usegalaxy.fr with me?

**Comment by llegregam** [comment]
I can share a link to the workflow. As the tools cannot be linked through output/input I cannot launch any jobs in the history. Here is the workflow:
https://workflow4metabolomics.usegalaxy.fr/workflow/editor?id=557b889a2f496bfb

**Comment by lecorguille** [comment]
I have just tested directly on the usegalaxy.fr instance.
I didn't expect that but the issue comes from the space in `format='csv, tabular'` it should be `format='csv,tabular'`

**Comment by llegregam** [comment]
Okey then, that is surprising! So I need to release a new wrapper with the fix, right?

**Comment by llegregam** [comment]
Thank you! :)
