### ISSUE TITLE
Tool request: MZMine

### ISSUE THREAD

**Issue by bernt-matthias** [workflow4metabolomics/tools-metabolomics#240]
I will work on mzMIne .. help welcome

- [ ] bioconda https://github.com/bioconda/bioconda-recipes/pull/40700
  - [ ] check if its possible to run GUI via container (`$DISPLAY`?)
  - [x] use `--help` and/or `--version` for tests https://github.com/bioconda/bioconda-recipes/pull/40700/commits/3ab75b20b1a597cf8f09128f217fec116eb070b5
  - [x] finish after new mzMine release https://github.com/bioconda/bioconda-recipes/pull/40700/commits/3ab75b20b1a597cf8f09128f217fec116eb070b5
- [ ] tool for batch processing
  - inputs
    - mzml files (as symlinks in input dir)
    - optional: annotation (csv), spectral library (user supplied / central reference data)
  - outputs
    - mgf file(s)
    - csv file(s)
    - future: mzMine project
  - set threads and tmp dir via config file (maybe in the future CLI parameter)
  - batch processing mode (input mzmine xml file(s))
- [ ] tool that creates and processes mzmine xml files

**Comment by yguitton** [comment]
Hi @bernt-matthias 

Really go idea, I'm not a docker expert, but maybe @Lain-inrae or @lecorguille can help at some point depending on your needs. It would be really cool to have mzMine batch processing implemented

Best
Yann

**Comment by bernt-matthias** [comment]
Wonderful. We may speed up development by starting tool development using a container. If I understood the mzmine developers right there should be one available (or at least easy to build one). We can switch to bioconda/biocontainers as soon as the mzmine bioconda recipe works.

**Comment by bernt-matthias** [comment]
I would like to have a VC on Tuesday (June 20th) with Robin Schmid. 10:00 or 13:00 CET (ie Berlin time) would work for both of us. Do you have any preferences regarding the time? Would be cool if some of you could join.

Ping @yguitton @Lain-inrae @lecorguille @chufz ..

**Comment by hechth** [comment]
@bernt-matthias I'd jump in if you don't mind - 1pm is preferred for me but can also make 10am.

**Comment by bernt-matthias** [comment]
Then lets make it 1pm. Anyone else: just ping me and I send you the VC details per mail.

**Comment by chufz** [comment]
I am also free 1pm and happy to join.

**Comment by yguitton** [comment]
Hi, sorry not available, but if possible keep me updated

Best

**Comment by bernt-matthias** [comment]
Hi there. 1st version over here: https://github.com/workflow4metabolomics/tools-metabolomics/pull/241 

Suggestions (in particular) if we could/should split output in multiple collections (or just use simple datasets). Problem is that we do not know what kind of outputs are configured in the output. 

1. We could define single dataset outputs for each possible output type (and add another select box allowing the user to choose [again] what is needed)
2. dynamically discovered outputs
3. A small set of collections that contain related outputs

I think 2 would not work in Galaxy workflows.

**Comment by bernt-matthias** [comment]
Bioconda recipe is ready in my opinion.

**Comment by bernt-matthias** [comment]
I'm pushing this to [IUC](https://github.com/galaxyproject/tools-iuc/pull/5462). Seems that the W4M repo is on hiatus at the moment.
