### ISSUE TITLE
Biocontainer not letting tool create subdirectory

### ISSUE THREAD

**Issue by llegregam** [workflow4metabolomics/tools-metabolomics#256]
So after a lot of coercion I was able to get a clean serve inside the biocontainers (with the right tool version) and was able to get a log from my tool. Here is the result:

![image](https://github.com/workflow4metabolomics/tools-metabolomics/assets/75795040/495d025b-1a79-4e35-8f02-07619543a65c)

Apparently we cannot create files during job execution? Since when?

_Originally posted by @llegregam in https://github.com/workflow4metabolomics/tools-metabolomics/issues/250#issuecomment-1822799314_

**Comment by bgruening** [comment]
This looks like a deployment problem and not a tool problem.

Does your tool respect the $TEMP variables?

**Comment by llegregam** [comment]
I was able to debug the error. My code was trying to recursively create folders and thus tried accessing the file system outside of the permitted directories. 
Thanks @sgsokol for helping me see this :)
