### ISSUE TITLE
Problem running physiofit 3.4.0 on the online instance

### ISSUE THREAD

**Issue by llegregam** [workflow4metabolomics/tools-metabolomics#271]
I recently updated the tool physiofit to version 3.4.0, and since then I get this message when I launch a job:
![image](https://github.com/workflow4metabolomics/tools-metabolomics/assets/75795040/a6a5651b-99c4-4817-971e-498e426b8488)

Any ideas where this is coming from?

**Comment by lecorguille** [comment]
Should be ok now !

**Comment by llegregam** [comment]
It is, thank you!
