### ISSUE TITLE
xcms 3.0 roiList

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/tools-metabolomics#91]
Hi I have tried dev version 3.0.0.0 and have a trouble ...
     http://galaxydev.workflow4metabolomics.org/u/yguitton/h/xcms30 

@lecorguille  can you help me
Yann

**Comment by yguitton** [comment]
@lecorguille 
for that peakpicking findChromPeaks-centWaveWithPredIsoROIs function it will be more efficiente to pass that ROIlist as an option (see help saying "**If** ROIs are submitted the first analysis step is omitted", the **IF** is essential that's mean that the ROIlist is not mandadory and can be automaticcaly built by centwave. 

that new centwave is one cool thing for xcms 3.0 as it is capable of automatically improving the peaklist using the peaks found by the first analysis step of centwave.

so please can you change a bit the .xml and put that ROIlist as FALSE by default and only experts will us roilists as input

Regards
Yann

**Comment by lecorguille** [comment]
@yguitton See https://github.com/workflow4metabolomics/xcms/pull/107
I was waiting for your approval

**Comment by lecorguille** [comment]
@yguitton Can I close this issue?
